### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Imaminer** [zawawawa/GatelessGateSharp#1]
When you get around to it :)
Rig ID (can't add to end of address like a /rig5)
Geographic location (I am in US but when I test on rig it went to eu.dwarfpool)
Watchdog (stops mining for some reason. need watchdog to try to restart it)
thanks

**Comment by zawawawa** [comment]
Thanks for the feedback. Geographic location is actually taken into account as the miner measures the actual response time of each server. I will make sure to include other features.

**Comment by UnclWish** [comment]
I think that worker name needed too.

**Comment by zawawawa** [comment]
That's the same as Rig ID. All done.

**Comment by UnclWish** [comment]
I set RigID but in nicehash statistics miner still shoed without worker name.
