### ISSUE TITLE
Password didn't works with custom pool

### ISSUE THREAD

**Issue by UnclWish** [zawawawa/GatelessGateSharp#13]
I set up the custom pool and I need non "x" password. I entered it into password field, but pool shows that GGS use "x" password. Maybe it's because of my password type... I entered password like this: MyRig:email@server.org
Please add suuport for those type of password.

**Comment by zawawawa** [comment]
If your settings still don't work with v1.1.4, please give me a screenshot of the Custom Pools tab page.

**Comment by UnclWish** [comment]
Yes, in 1.1.4 the same situation.
Here is the screen: https://prnt.sc/hmpsdx

**Comment by zawawawa** [comment]
It should work by now,

**Comment by UnclWish** [comment]
No, it's still didn't work in 1.1.21 version.

**Comment by zawawawa** [comment]
I think it is the pool, but I will check it one last time.
