### ISSUE TITLE
Why only 8 graphics cards are supported at most?

### ISSUE THREAD

**Issue by Sfinx-vrn** [zawawawa/GatelessGateSharp#18]
Hi!
I have 2rigs for 9 and 11 cards. I wanted to test your software, but I was disappointed to find that I only maintain a maximum of 8 cards. And this is at the time when motherboards are issued for 13-20 cards. 
Dear developers! Please correct this annoying restriction.
Thank in advance

**Comment by zawawawa** [comment]
I will get to this issue soon!

**Comment by zawawawa** [comment]
This limit is lifted already.
