### ISSUE TITLE
Stopped reporting temp, activity and mem specs

### ISSUE THREAD

**Issue by cooler0918** [zawawawa/GatelessGateSharp#22]
H, Thank you for the software, which was working great, until I flash the bios on one of my cards.  I have a Gigabyte Aorus RX580, which was running stock bios for while and that worked fine.  I flashed said bios to a modded one and while I did get more hasrate out of that card, the software stopped recognising any of my cards as RX580.  Instead it listed them as Ellesmere, and it would not longer report the stats.  Furthermore, mu other card, a XFX RX580 started producing the "Reject share error, low difficulty".  Both the cards are 8G and I tried all kinds of different settings.

**Comment by cooler0918** [comment]
Oh, forgot to mention. I am running the 1.1.5 version

**Comment by zawawawa** [comment]
This is a problem with the modded BIOS. I am planning to update the hardware monitoring/management portion of GGS in the near future.

**Comment by zawawawa** [comment]
Please try v1.2.1 with Adrenalin 12.2.2. Voltage readings probably won't work, but there is not much I can do about it right now.
