### ISSUE TITLE
all stats of gpu fan, temp, core, mem as one gpu (tested in 1.13 and 1.12, in 1.08 was ok)

### ISSUE THREAD

**Issue by azicks** [zawawawa/GatelessGateSharp#30]
![1](https://user-images.githubusercontent.com/34977658/34521204-203ecf9c-f0bf-11e7-85f7-c8f1dc6a1246.png)

**Comment by gennadiv** [comment]
Yes, the farther the worse . I have the same thing as you.and for double production, nothing is done to increase the speed and add another coin to double

**Comment by azicks** [comment]
Now ok.
