### ISSUE TITLE
mV Showing incorrect values

### ISSUE THREAD

**Issue by ColossusFX** [zawawawa/GatelessGateSharp#39]
![ggsharp_mverror](https://user-images.githubusercontent.com/17220028/34946773-0ec13b66-fa00-11e7-871d-e393463638d7.jpg)

Not sure what is happening with this..

This is a rig that potentially has a bad GPU.

So not sure if this is software or hardware related.

**Comment by ColossusFX** [comment]
![ggsharp_mverror2](https://user-images.githubusercontent.com/17220028/34946877-68db3c1e-fa00-11e7-8320-38872f88d041.jpg)

Now one is showing 40mV

**Comment by zawawawa** [comment]
This is yet another driver issue. It will be fixed in the next version.

**Comment by cibertea** [comment]
Have the same issue, i also tested the overclock and does not work.
I have 6 Saphire RX570 Nitro +, with the blockchain drivers, also noted that MSI afterburner, and trixx version 6.4 stopped working, the only tool that works but it is slow is Trixx 6.5 ( it was taken from saphire site, ).
Any idea on this ?
Only happens with the blockchain drivers, also cant find the option for compute mode...

**Comment by zawawawa** [comment]
Fixed!
