### ISSUE TITLE
Don't save option "Disable promt before auto-start"

### ISSUE THREAD

**Issue by UnclWish** [zawawawa/GatelessGateSharp#4]
It's a bug in 1.1.0 alpha. GGS didn't save option "Disable promt before auto-start". Untill program opened option is enabled. Restarting GGS and it asking on start and option is disabled. I deleted GatelessGateSharp.sqlite and tune program again, but it didn't helps.

**Comment by zawawawa** [comment]
Fixed in v1.1.1. Thanks!
