### ISSUE TITLE
Add Electroneum Support

### ISSUE THREAD

**Issue by cibertea** [zawawawa/GatelessGateSharp#40]
Hi, when we add a costum pool there is no space to insert the wallet adress, this coin is cryptonight based so the monero miner will do for it.

This would allow the minner to mine other coins based on the suported algoritms.

Like the minner, a litle better hash rate than Claymore, GOOD WORK !

have  to test the latest alpha

**Comment by zawawawa** [comment]
Just put the wallet address as a username, and you should be fine. Don't forget to set a password, though.
