### ISSUE TITLE
auto start + auto mining when setting failed

### ISSUE THREAD

**Issue by besta04** [zawawawa/GatelessGateSharp#41]
Hi, i had an issue, when i accidentally inputted the wrong number (too low core voltage), i had a bsod and then system restarted. After that the program started automatically and started mining using the same settings, bsod again, it keeps like that so i had to force close via taskmgr before the mining starts. After that, i uninstall and reinstall, but the settings retained.

My solution is after uninstall, i delete all the file from C and registry named "gateless", then install, after that the settings reset.

Could you please add a workaround for this? Thank you

P.S. Nice miner btw. keep up the good work!

**Comment by zawawawa** [comment]
You can hold one of the shift keys in order to prevent auto-start.
