### ISSUE TITLE
Bug with 1 selected GPU

### ISSUE THREAD

**Issue by UnclWish** [zawawawa/GatelessGateSharp#5]
Situation:
Two cards RX 580. Selected only 1st card. With auto-start GSS allways starts normal mining on 1st card.
If press "Stop", than press "Start" sometimes GSS begin to mine on 2nd card. 1st is not mine.

**Comment by zawawawa** [comment]
That's no good... Thanks for reporting!

**Comment by zawawawa** [comment]
There was an absolutely critical bug. It will be fixed in Version 1.1.2 alpha. Thanks again!
