### ISSUE TITLE
RX550 GatelessGateSharp configuration

### ISSUE THREAD

**Issue by pe4enko** [zawawawa/GatelessGateSharp#54]
Hi.
What is the best configuration for RX 550 video card on CryptoNight algorithm?

Now i have about 340 H/s for one video card.
But on OLD GatelessGate miner i have about 490 H/s, but it not very stable. 

this configuration
{
"name": "xmr",
"algorithm": "cryptonight",
"rawintensity": "420",
"worksize": "8",
"gpu-threads": "2"
}

Is it posible to get 490 H/s on GatelessGateSharp miner?

**Comment by UnclWish** [comment]
Try toset raw intensity 60 in GGS.

**Comment by d0n-miner1** [comment]
Hey can I have a copy of the old gateless miner pls??

**Comment by pe4enko** [comment]
> Hey can I have a copy of the old gateless miner pls??
https://yadi.sk/d/AjQb4jZn3SWJd9

**Comment by d0n-miner1** [comment]
this is great. 
thanks a bunch man.

**Comment by afrizalnet** [comment]
```
{
"name": "xmr",
"algorithm": "cryptonight",
"rawintensity": "420",
"worksize": "8",
"gpu-threads": "2"
}
```

My RX 550 got 430 h/s with this config using old gateless.
thank you @pe4enko

**Comment by UnclWish** [comment]
@afrizalnet Try rawintensity 458-460.

**Comment by afrizalnet** [comment]
Intensity 420 is very stable on my PC.

@unclwish thank you for your suggestions.
