### ISSUE TITLE
 GPU death

### ISSUE THREAD

**Issue by farcryamd** [zawawawa/GatelessGateSharp#57]
![captura de tela 6](https://user-images.githubusercontent.com/37093701/37012193-30778a14-20d2-11e8-92a3-b3008016aa2c.png)

configuration
"algorithm": "cryptonight",
  "rawintensity": "114",
  "worksize": "8",
  "gpu-threads": "2",

I am using Gateless Gate Sharp 1.2.18, but it presents the above problem. Driver Win10-64Bit-Crimson-ReLive-Beta-Blockchain-Workloads

**Comment by farcryamd** [comment]
![screenshot_20180306001821](https://user-images.githubusercontent.com/37093701/37012543-01d6ab20-20d4-11e8-8b6f-896341313544.png)

**Comment by zawawawa** [comment]
GGS does not support Blockchain drivers.
