### ISSUE TITLE
Recommended rawdensity for RX 550

### ISSUE THREAD

**Issue by afrizalnet** [zawawawa/GatelessGateSharp#59]
Please share your recommended rawdensity for RX 550 Baffin to get optimized hashrate for mining Monero?

Currently I use rawdensity 60 and I got 330 h/s on Nicehash.

Thank you

**Comment by UnclWish** [comment]
You must try variants - 64, 40, 48, 56. Select most speedable and fine tune +-1.

**Comment by afrizalnet** [comment]
Than you.
Its works perfect on my rig.
RX 550 Baffin I got 420 h/s with rawdensity 400 and 480 using old gateless, but not on GGS

**Comment by zawawawa** [comment]
Please try v1.3.x.
