### ISSUE TITLE
Alpha

### ISSUE THREAD

**Issue by KinGGuN73** [zawawawa/GatelessGateSharp#6]
Can we have acces to the Gateless_Gate_Sharp_1.1.1_alpha source please ? 
This is a good job, keep it up !

**Comment by KinGGuN73** [comment]
And when can we use Equihash ?

**Comment by UnclWish** [comment]
> Can we have acces to the Gateless_Gate_Sharp_1.1.1_alpha source please ?
This is a good job, keep it up !
Look into "Branch"

**Comment by zawawawa** [comment]
Equihash will be available very soon...
