### ISSUE TITLE
Recommended rawintensity for RX 570 8Gb

### ISSUE THREAD

**Issue by afrizalnet** [zawawawa/GatelessGateSharp#60]
Please share your recommended rawintensity for RX 570 Micron to get optimized hashrate for mining Monero?

Currently I use Old Gateless Gate with rawintensity 540 and I got 888 h/s on Nicehash pool.

Thank you

**Comment by zawawawa** [comment]
As I clearly stated numerous times, I do not provide support for the original Gateless Gate. The new Gateless Gate Sharp has an automatic optimizer.
