### ISSUE TITLE
Payout issue with gateless gate on z-nomp

### ISSUE THREAD

**Issue by trextrader** [zawawawa/GatelessGateSharp#61]
**Please see screenshot and conf file.**  All ethOS rigs running claymore-zcash working no issues. One windows rig with Vegas is hashing away and I see it has 26.02 shares as of current but its not paying like the rest of them and balance is also showing zero.  Also when I launch the miner there is no GUI other than the typical sgminer wommand window showing a table with keyboard inputs, so not sure perhaps I havge the wrong version(?)   The only change I made was to set the wallet in the config file to my wallet under "MAIN" and let it roll (see below). It shows up as Vega10, everything else is working, just not paying and balance is still 0.00 and have never seen that happen before.  Also below is the config file so not sure if I have something messed up there, it seems pretty straight forward so any ideas would be greatly appreciated on how to resolve the Vega10 rig (which is actually 9 vega 56's at the moment, orig bios, light oc using overdriveNtool.  Any ideal OC settings for Vega 56 if you know and i will test it.

![znomp pool workers vega10 payout balance issue png](https://user-images.githubusercontent.com/24986102/38169908-67539264-3534-11e8-92f4-81d6a815e91b.jpg)

**Bat launch File: gatelessgate-Zcash-platform0**

@echo off
set GPU_FORCE_64BIT_PTR 1
set GPU_MAX_HEAP_SIZE 100
set GPU_USE_SYNC_OBJECTS 1
set GPU_MAX_ALLOC_PERCENT 100
set GPU_SINGLE_ALLOC_PERCENT 100
gatelessgate.exe --gpu-platform 0 --default-config gatelessgate-Zcash.conf
pause

**Config file: gatelessgate-Zcash.conf**

{
  "algorithm": "equihash",
  "worksize": "256",
  "gpu-threads": "2",
  "load-balance": true,

  "auto-fan": true,
  "temp-cutoff": "90",
  "temp-overheat": "85",
  "temp-target": "75",
  
  "pools": [
    {
      "name": "MAIN",
      "user": "i8NGaav4ybLvD2JPqq35x9tnV9n8jsyMS9.Vega10", **// This is where I added in my BCI wallet**
      "pass": "z",
      "quota": "99;stratum+tcp://pool.bci-server.com:3857"
    },
    {
	  "__comment": "Please keep this entry. Otherwise, I won't be able to continue open-source development. - zawawa",
      "name": "DEVFEE",
      "user": "t1NwUDeSKu4BxkD58mtEYKDjzw5toiLfmCu", **// Of course, no screwing the dev over as I am dev too and it sucks when people do that**
      "pass": "z",
      "quota": "1;stratum+tcp://us1-zcash.flypool.org:3333"
    }
  ]
}

**Comment by zawawawa** [comment]
As I clearly stated numerous times, I do not provide support for the original Gateless Gate.

**Comment by zawawawa** [comment]
Wait a sec... You do have a wrong version. Please use "Gateless Gate Sharp."
