### ISSUE TITLE
Custom Pool Settings Not Working

### ISSUE THREAD

**Issue by VirtualRon** [zawawawa/GatelessGateSharp#63]
Hello,
Great miner, everything works except for my custom pool settings. I would like to use miningpool.hub but doesn't seem to take settings. Is there a doc I missed somewhere?

Thanks
Ron

**Comment by zawawawa** [comment]
Could I see screenshots of the Dashboard and Custom Pools tab pages?

**Comment by jch9678** [comment]
Miningpoolhub works for me.

Password still doesn't get passed on custom pools though.

**Comment by skablast** [comment]
When Sumocoin was added, Cryptonight v7 got lost.(its not available in the menu of custom pool).
IF "IF" a benchmark for V7 was run, then even selecting Custom pool for monero, GGS choose the default pool. That btw, is a good pool...

**Comment by zawawawa** [comment]
This is a real compatibility issue. I will address it very soon.

**Comment by UnclWish** [comment]
Better to do that. Someone can not use GGS OC settings, but may use Radeon Settings for settings.

**Comment by zawawawa** [comment]
This is a wrong issue, @UnclWish.

**Comment by VirtualRon** [comment]
![gateless-2](https://user-images.githubusercontent.com/18472402/38714439-e43b52ec-3e9b-11e8-90ee-774980e76c98.jpg)
![gateless-3](https://user-images.githubusercontent.com/18472402/38714440-e450a2dc-3e9b-11e8-8e41-adbf21bd6bdf.jpg)
![gateless-4](https://user-images.githubusercontent.com/18472402/38714441-e471eaaa-3e9b-11e8-84b3-e77394012609.jpg)

Sorry, was out of town...here's the shots of my settings. Also note on #4 the 580 is working but the 7990's are not. Drivers are up to dateand they work with some other miners. Just curious

**Comment by UnclWish** [comment]
@zawawawa Yes, sorry. My mistake.

**Comment by zawawawa** [comment]
This issue has been fixed with v1.3.5, I think. If not, please reopen the issue.
