### ISSUE TITLE
Cycle error at startup

### ISSUE THREAD

**Issue by pe4enko** [zawawawa/GatelessGateSharp#64]
After try to start Gateless_Gate_Sharp_1.3.2_prealpha.7z
i have error in loop "Unhandled Thread Exception"
![dbfffe53-65c4-4bce-8d43-f37015b7eca3](https://user-images.githubusercontent.com/822445/38472221-4faa6708-3b85-11e8-84ae-0d770acd96b4.jpg)

**Comment by zawawawa** [comment]
Please delete everything in "%AppData%\GatelessGateSharp".
