### ISSUE TITLE
Radeon Settings closes after launching GGS 1.3.2 preA

### ISSUE THREAD

**Issue by UnclWish** [zawawawa/GatelessGateSharp#66]
Finded strange bug - when GGS launched, after 15-30 seconds RadeonSettings.exe just disappears from memory. If during GGS running and mining launch RadeonSettings again and even didn't close they window just looking on it - it closes anyway after ~20 seconds...
No errors on events...
If close GGS and run RadeonSettings they work normal...

**Comment by zawawawa** [comment]
That's by design as Radeon Settings interfere with GGS.

**Comment by UnclWish** [comment]
In this case add at least relaunch of Radeon Settings after closing GGS.
