### ISSUE TITLE
Add support for Windows 10 April Update

### ISSUE THREAD

**Issue by zawasp** [zawawawa/GatelessGateSharp#70]
With the latest Windows 10 update, GatelessGateSharp does not start (it freezes at startup, displaying the GGS logo only). I tried with recommended AMD Adrenalin drivers, and also the latest ones, 18.4.1 which add support for Windows 10 April Update.

Thank you for your work.

**Comment by zawasp** [comment]
I did. DDU, put 18.3.4. The only difference between the rigs where it works and where it doesn't is the latest Windows update. AFAIK, they changed the driver model, as more apps added support for it - GPU-Z included:
https://www.techpowerup.com/download/techpowerup-gpu-z/

"Added WDDM 2.4 support for Windows 10 RS4 / April Update / Spring Creators Update"

**Comment by UnclWish** [comment]
I have installed 1803 April Update. Installed 18.4.1 and have issuies in miners. Then I use DDU and installed 18.3.4 and all goes normal.

**Comment by zawasp** [comment]
I traced the problem to the onboard Intel HD Graphics 4000 (and it's latest driver). I disabled it and now it starts. It's strange, as until this Windows update it worked properly together with the onboard GPU. Maybe there's a problem enumerating the GPUs at startup?

**Comment by zawawawa** [comment]
Mixing GPU's from different vendors is almost always a bad idea. Also, Intel's OpenCL drivers are known to be notoriously buggy. I wouldn't even touch them.
